dist: bionic

language: go
go: 1.13.1

services:
  - docker

script:
  - go test
  - go build -ldflags="-s -w"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t maslick/grafana-telegram-proxy .

after_success:
  - test $TRAVIS_BRANCH = "master" && docker push maslick/grafana-telegram-proxy